(function ($) {
  $.Redactor.opts.langs['ru'] = {
    "format": "Формат",
    "image": "Картинка",
    "file": "Файл",
    "link": "Ссылка",
    "bold": "Полужирный",
    "italic": "Курсив",
    "deleted": "Зачеркнутый",
    "underline": "Подчеркнутый",
    "bold-abbr": "B",
    "italic-abbr": "I",
    "deleted-abbr": "S",
    "underline-abbr": "U",
    "lists": "Списки",
    "link-insert": "Вставить ссылку",
    "link-edit": "Редактировать ссылку",
    "link-in-new-tab": "Открыть ссылку в новом табе",
    "unlink": "Удалить ссылку",
    "cancel": "Отменить",
    "close": "Закрыть",
    "insert": "Вставить",
    "save": "Сохранить",
    "delete": "Удалить",
    "text": "Текст",
    "edit": "Редактировать",
    "title": "Title",
    "paragraph": "Обычный текст",
    "quote": "Цитата",
    "code": "Код",
    "heading1": "Заголовок 1",
    "heading2": "Заголовок 2",
    "heading3": "Заголовок 3",
    "heading4": "Заголовок 4",
    "heading5": "Заголовок 5",
    "heading6": "Заголовок 6",
    "filename": "Имя файла",
    "optional": "необязательно",
    "unorderedlist": "Ненумерованный список",
    "orderedlist": "Нумерованный список",
    "outdent": "Убрать отступ",
    "indent": "Добавить отступ",
    "horizontalrule": "Линия",
    "upload-label": "Перетащите файл или ",
    "accessibility-help-label": "Редактор форматированного текста",
    "caption": "Подпись",
    "bulletslist": "Маркеры",
    "numberslist": "Нумерация",
    "image-position": "Position",
    "none": "None",
    "left": "Left",
    "right": "Right",
    "center": "Center",
    "video": "Видео",
    "video-html-code": "Код для встраивания видео или ссылка на Youtube/Vimeo",
    "table": "Таблица",
    "insert-table": "Вставить таблицу",
    "insert-row-above": "Вставить строку сверху",
    "insert-row-below": "Вставить строку снизу",
    "insert-column-left": "Вставить стобец слева",
    "insert-column-right": "Вставить столбец справа",
    "add-head": "Добавить заголовок",
    "delete-head": "Удалить заголовок",
    "delete-column": "Удалить столбец",
    "delete-row": "Удалить строку",
    "delete-table": "Удалить таблицу",
    "align": "Выравнивание",
    "align-left": "Выравнивание по левому краю",
    "align-center": "Выравнивание по центру",
    "align-right": "Выравнивание по правому краю",
    "align-justify": "Выравнивание по ширине"
  };
})(jQuery);