<script>
    (function (_, $) {
        _.tr({
            "gdpr.klaro_accept_all": '{__("gdpr.klaro_accept_all", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_accept_selected": '{__("gdpr.klaro_accept_selected", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_close": '{__("gdpr.klaro_close", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_consent_modal_description": '{__("gdpr.klaro_consent_modal_description", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_consent_modal_title": '{__("gdpr.klaro_consent_modal_title", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_consent_notice_change_description": '{__("gdpr.klaro_consent_notice_change_description",['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_consent_notice_title": '{__("gdpr.klaro_consent_notice_title", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_consent_notice_description": '{__("gdpr.klaro_consent_notice_description", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_consent_notice_learn_more": '{__("gdpr.klaro_consent_notice_learn_more", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_consent_notice_testing": '{__("gdpr.klaro_consent_notice_testing", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_contextual_consent_accept_always": '{__("gdpr.klaro_contextual_consent_accept_always", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_contextual_consent_accept_once": '{__("gdpr.klaro_contextual_consent_accept_once", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_contextual_consent_description": '{__("gdpr.klaro_contextual_consent_description", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_decline": '{__("gdpr.klaro_decline", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_ok": '{__("gdpr.klaro_ok", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_powered_by": '{__("gdpr.klaro_powered_by", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_privacy_policy_title": '{__("gdpr.klaro_privacy_policy_title", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_privacy_policy_name": '{__("gdpr.klaro_privacy_policy_name", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_service": '{__("gdpr.klaro_service", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_services": '{__("gdpr.klaro_services", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.strictly_necessary_cookies_title": '{__("gdpr.strictly_necessary_cookies_title", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.strictly_necessary_cookies_description": '{__("gdpr.strictly_necessary_cookies_description", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.performance_cookies_title": '{__("gdpr.performance_cookies_title", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.performance_cookies_description": '{__("gdpr.performance_cookies_description", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.functional_cookies_title": '{__("gdpr.functional_cookies_title", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.functional_cookies_description": '{__("gdpr.functional_cookies_description", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.marketing_cookies_title": '{__("gdpr.marketing_cookies_title", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.marketing_cookies_description": '{__("gdpr.marketing_cookies_description", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_service_purpose": '{__("gdpr.klaro_service_purpose", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_service_purposes": '{__("gdpr.klaro_service_purposes", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_service_required_description": '{__("gdpr.klaro_service_required_description", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.eway_cookies_title": '{__("gdpr.eway_cookies_title", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.eway_cookies_description": '{__("gdpr.eway_cookies_description", ['skip_live_editor' => true])|escape:"javascript"}',
            "save": '{__("save", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.disable_all_description": '{__("gdpr.disable_all_description", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.disable_all_title": '{__("gdpr.disable_all_title", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.opt_out_description": '{__("gdpr.opt_out_description", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.opt_out_title": '{__("gdpr.opt_out_title", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.klaro_service_required_title": '{__("gdpr.klaro_service_required_title", ['skip_live_editor' => true])|escape:"javascript"}',
            "gdpr.uk_cookies_law": '{__("gdpr.uk_cookies_law", ['skip_live_editor' => true])|escape:"javascript"}',
        });
    })(Tygh, Tygh.$);
</script>

{script src="js/addons/gdpr/func.js"}
